[book]
title = "Notes"
authors = ["Antonio Gelameris"]
language = "en"
multilingual = false
src = "src"

[preprocessor.links]
renderers = ["html"]
some_extra_feature = true

[output.html]
site-url = "https://notes.toniogela.dev/"
git-repository-url = "https://github.com/TonioGela/mdbook"
additional-css = ["custom.css"]
default-theme = "Ayu"
preferred-dark-theme = "Ayu"
no-section-label = true
input-404 = "404.md"