[build]
  publish = "book"
  command = "curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.7/mdbook-v0.4.7-x86_64-unknown-linux-gnu.tar.gz | tar xvz && ./mdbook build"

[[plugins]]
  package = "netlify-plugin-inline-source"
  [plugins.inputs]
    attribute = "inline"
    compress = true

[[plugins]]
package = "netlify-plugin-checklinks"
  [plugins.inputs]
  checkExternal = true